//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContentLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ContentLocalization", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///Effective training in Fresno, CA&lt;/p&gt;
        ///&lt;p&gt;
        ///When I decided to move the HouseOfBurt webpage form it&apos;s original &lt;a href=&quot;http://houseofburt.wordpress.com/&quot;&gt;Wordpress-default themed glory&lt;/a&gt; it quickly became obvious out that my HTML skills from 1997 were not going to be of much help in the Modern Web. I took the introductory course in HTML 5/Javascript from &lt;a href=&quot;http://www.codecademy.com/&quot;&gt;Codeademy&lt;/a&gt;, but wanted to get something more in-depth. Luckily for myself I happen to live in Fresno, CA, hom [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Article10Content {
            get {
                return ResourceManager.GetString("Article10Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;/p&gt;.
        /// </summary>
        internal static string Article11Content {
            get {
                return ResourceManager.GetString("Article11Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Welcome to the home of HouseOfBurt. Here you will find access to several utilities that are targeted towards making life with computers a little easier than they are now. You can look at the current software offerings under the &lt;a title=&quot;Products&quot; href=&quot;http://houseofburt.wordpress.com/products/&quot;&gt;Products&lt;/a&gt; page. If you have any questions/comments please feel free to contact me.&lt;/p&gt;.
        /// </summary>
        internal static string Article1Content {
            get {
                return ResourceManager.GetString("Article1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Version 1.4 of Service Tag Reporter has been released. This release uses the new Dell SOAP service to retrieve accurate information directly from Dell&amp;#8217;s Asset tracking servers. Several other speed improvements have been included as well.&lt;/p&gt;
        ///&lt;p&gt;Service Tag reporter is a software based utility that fetches Dell warranty information from Dell&amp;#8217;s servers.&lt;br /&gt;
        ///Enter in the desired service tags into the left hand input window and click &amp;#8216;Query Tags&amp;#8217; to get a list of products and thei [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Article2Content {
            get {
                return ResourceManager.GetString("Article2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Version 1.2 of File Zapper has been released. This release has a revamped GUI and uses a quicker and more secure connection method to remote workstations&lt;/p&gt;
        ///&lt;p&gt;File Zapper allows for the removal of unwanted files on multiple machines remotely. The application connects to each specified machine and uses the current user’s credentials to effect removal of the desired file or folder. Verbose logging is included and the application is capable of clearing both individual files and folders.&lt;/p&gt;
        ///&lt;a href=&quot;htt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Article3Content {
            get {
                return ResourceManager.GetString("Article3Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Version 1.4.1 of Service Tag Reporter has been released. This release features additional speed improvements when querying large numbers of Service Tags and Bug Fixes. If you have any questions/comments let me know!&lt;/p&gt;
        ///&lt;p&gt;&lt;a title=&quot;Service Tag Reporter Download&quot; href=&quot;http://db.tt/wmDB9FGf&quot;&gt;Download it here&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;About Service Tag Reporter&lt;/p&gt;
        ///&lt;p&gt;Service Tag reporter is a software based utility that fetches Dell warranty information from Dell’s servers.&lt;br /&gt;
        ///Enter in the desired service tags i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Article4Content {
            get {
                return ResourceManager.GetString("Article4Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Version 1.1 of &lt;a title=&quot;HP Warranty Reporter&quot; href=&quot;http://houseofburt.herokuapp.com/products/1&quot;&gt;HP Warranty Reporter&lt;/a&gt; has been released. This release includes GUI updates and no longer requires the user to know the product code for warranty retrieval.&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;http://houseofburt.files.wordpress.com/2012/05/screenshot.png&quot;&gt;&lt;img title=&quot;HP Warranty Reporter Screenshot&quot; src=&quot;http://houseofburt.files.wordpress.com/2012/05/screenshot.png?w=150&amp;#038;h=84&quot; alt=&quot;HP Warranty Reporter&quot;/&gt;&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Article5Content {
            get {
                return ResourceManager.GetString("Article5Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;HP updated their website recently and the older 1.1 versions of HP Warranty Reporter started having problems parsing warranty data properly. An update has been released &lt;a title=&quot;HP Warranty Reporter Download&quot; href=&quot;http://db.tt/ERPKxCmw&quot;&gt;here&lt;/a&gt; that contains a new EXE that parses warranty dates properly. We are recommending that everyone use the new EXE and not the old one.&lt;/p&gt;.
        /// </summary>
        internal static string Article6Content {
            get {
                return ResourceManager.GetString("Article6Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Service Tag Reporter version 1.5 is a performance and usability upgrade. New features include:&lt;/p&gt;
        ///&lt;p&gt;* better performance of large set of service tags&lt;/p&gt;
        ///&lt;p&gt;* more informative feedback if the a service tag cannot be requested remotely&lt;/p&gt;
        ///&lt;p&gt;* the ability to hide the &amp;#8216;Query Service Tag Remotely&amp;#8217; option if you don&amp;#8217;t want it&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;http://houseofburt.files.wordpress.com/2013/09/servicetagreporter150.png&quot;&gt;&lt;img alt=&quot;Image&quot; src=&quot;http://houseofburt.files.wordpress.com/2013/09/s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Article7Content {
            get {
                return ResourceManager.GetString("Article7Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;I recently gave a talk at the Central California .Net User Group about &lt;a href=&quot;http://monogame.net/&quot;&gt;Monogame&lt;/a&gt;. It was my first major speaking engagement since becoming a professional developer and I was glad to share about a technology I&apos;ve enjoyed using. For those who may be unfamiliar with the technology, Monogame is an Open Source implementation of Microsoft&apos;s XNA framework. XNA was built initially with the goal of making it easy to build games for Microsoft devices like the XBox or Windows Phone [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Article8Content {
            get {
                return ResourceManager.GetString("Article8Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Service Tag Reporter version 1.6 is a major perofrmance enhancement. New features include:&lt;/p&gt;
        ///&lt;p&gt;* better performance in fetching warranties&lt;/p&gt;
        ///&lt;p&gt;* invalid service tags no longer populate the results grid&lt;/p&gt;
        ///&lt;p&gt;* Dells warranty servers starting reporting the presence of &apos;digital warranties&apos; that only provided software download protection. These are now discarded&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;http://houseofburt.files.wordpress.com/2013/09/servicetagreporter150.png&quot;&gt;&lt;img alt=&quot;Image&quot; src=&quot;http://houseofburt.files [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Article9Content {
            get {
                return ResourceManager.GetString("Article9Content", resourceCulture);
            }
        }
    }
}
