//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfBurt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HouseOfBurt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///Effective training in Fresno, CA&lt;/p&gt;
        ///&lt;p&gt;
        ///When I decided to move the HouseOfBurt webpage form it&apos;s original &lt;a href=&quot;http://houseofburt.wordpress.com/&quot;&gt;Wordpress-default themed glory&lt;/a&gt; it quickly became obvious out that my HTML skills from 1997 were not going to be of much help in the Modern Web. I took the introductory course in HTML 5/Javascript from &lt;a href=&quot;http://www.codecademy.com/&quot;&gt;Codeademy&lt;/a&gt;, but wanted to get something more in-depth. Luckily for myself I happen to live in Fresno, CA, hom [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Article10Content {
            get {
                return ResourceManager.GetString("Article10Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;/p&gt;.
        /// </summary>
        public static string Article11Content {
            get {
                return ResourceManager.GetString("Article11Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Welcome to the home of HouseOfBurt. Here you will find access to several utilities that are targeted towards making life with computers a little easier than they are now. You can look at the current software offerings under the &lt;a title=&quot;Products&quot; href=&quot;http://houseofburt.wordpress.com/products/&quot;&gt;Products&lt;/a&gt; page. If you have any questions/comments please feel free to contact me.&lt;/p&gt;.
        /// </summary>
        public static string Article1Content {
            get {
                return ResourceManager.GetString("Article1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Version 1.4 of Service Tag Reporter has been released. This release uses the new Dell SOAP service to retrieve accurate information directly from Dell&amp;#8217;s Asset tracking servers. Several other speed improvements have been included as well.&lt;/p&gt;
        ///&lt;p&gt;Service Tag reporter is a software based utility that fetches Dell warranty information from Dell&amp;#8217;s servers.&lt;br /&gt;
        ///Enter in the desired service tags into the left hand input window and click &amp;#8216;Query Tags&amp;#8217; to get a list of products and thei [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Article2Content {
            get {
                return ResourceManager.GetString("Article2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Version 1.2 of File Zapper has been released. This release has a revamped GUI and uses a quicker and more secure connection method to remote workstations&lt;/p&gt;
        ///&lt;p&gt;File Zapper allows for the removal of unwanted files on multiple machines remotely. The application connects to each specified machine and uses the current user’s credentials to effect removal of the desired file or folder. Verbose logging is included and the application is capable of clearing both individual files and folders.&lt;/p&gt;
        ///&lt;a href=&quot;htt [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Article3Content {
            get {
                return ResourceManager.GetString("Article3Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Version 1.4.1 of Service Tag Reporter has been released. This release features additional speed improvements when querying large numbers of Service Tags and Bug Fixes. If you have any questions/comments let me know!&lt;/p&gt;
        ///&lt;p&gt;&lt;a title=&quot;Service Tag Reporter Download&quot; href=&quot;http://db.tt/wmDB9FGf&quot;&gt;Download it here&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;About Service Tag Reporter&lt;/p&gt;
        ///&lt;p&gt;Service Tag reporter is a software based utility that fetches Dell warranty information from Dell’s servers.&lt;br /&gt;
        ///Enter in the desired service tags i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Article4Content {
            get {
                return ResourceManager.GetString("Article4Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Version 1.1 of &lt;a title=&quot;HP Warranty Reporter&quot; href=&quot;http://houseofburt.herokuapp.com/products/1&quot;&gt;HP Warranty Reporter&lt;/a&gt; has been released. This release includes GUI updates and no longer requires the user to know the product code for warranty retrieval.&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;http://houseofburt.files.wordpress.com/2012/05/screenshot.png&quot;&gt;&lt;img title=&quot;HP Warranty Reporter Screenshot&quot; src=&quot;http://houseofburt.files.wordpress.com/2012/05/screenshot.png?w=150&amp;#038;h=84&quot; alt=&quot;HP Warranty Reporter&quot;/&gt;&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Article5Content {
            get {
                return ResourceManager.GetString("Article5Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;HP updated their website recently and the older 1.1 versions of HP Warranty Reporter started having problems parsing warranty data properly. An update has been released &lt;a title=&quot;HP Warranty Reporter Download&quot; href=&quot;http://db.tt/ERPKxCmw&quot;&gt;here&lt;/a&gt; that contains a new EXE that parses warranty dates properly. We are recommending that everyone use the new EXE and not the old one.&lt;/p&gt;.
        /// </summary>
        public static string Article6Content {
            get {
                return ResourceManager.GetString("Article6Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Service Tag Reporter version 1.5 is a performance and usability upgrade. New features include:&lt;/p&gt;
        ///&lt;p&gt;* better performance of large set of service tags&lt;/p&gt;
        ///&lt;p&gt;* more informative feedback if the a service tag cannot be requested remotely&lt;/p&gt;
        ///&lt;p&gt;* the ability to hide the &amp;#8216;Query Service Tag Remotely&amp;#8217; option if you don&amp;#8217;t want it&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;http://houseofburt.files.wordpress.com/2013/09/servicetagreporter150.png&quot;&gt;&lt;img alt=&quot;Image&quot; src=&quot;http://houseofburt.files.wordpress.com/2013/09/s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Article7Content {
            get {
                return ResourceManager.GetString("Article7Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;I recently gave a talk at the Central California .Net User Group about &lt;a href=&quot;http://monogame.net/&quot;&gt;Monogame&lt;/a&gt;. It was my first major speaking engagement since becoming a professional developer and I was glad to share about a technology I&apos;ve enjoyed using. For those who may be unfamiliar with the technology, Monogame is an Open Source implementation of Microsoft&apos;s XNA framework. XNA was built initially with the goal of making it easy to build games for Microsoft devices like the XBox or Windows Phone [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Article8Content {
            get {
                return ResourceManager.GetString("Article8Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Service Tag Reporter version 1.6 is a major perofrmance enhancement. New features include:&lt;/p&gt;
        ///&lt;p&gt;* better performance in fetching warranties&lt;/p&gt;
        ///&lt;p&gt;* invalid service tags no longer populate the results grid&lt;/p&gt;
        ///&lt;p&gt;* Dells warranty servers starting reporting the presence of &apos;digital warranties&apos; that only provided software download protection. These are now discarded&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;http://houseofburt.files.wordpress.com/2013/09/servicetagreporter150.png&quot;&gt;&lt;img alt=&quot;Image&quot; src=&quot;http://houseofburt.files [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Article9Content {
            get {
                return ResourceManager.GetString("Article9Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;File Zapper allows for the removal of unwanted files on multiple machines remotly. The application connects to each specified machine and uses the current user&amp;#8217;s creditials to effect removal of the desired file or folder.&lt;/p&gt;
        ///
        ///    &lt;p&gt;Enter the file path of the prospective file you wish to delete or browse the desired path on your own workstation. Enter the names of the computers you wish to remove the files on and click &amp;#8216;Zap Files&amp;#8217; to remove the desired files form the workstations. Th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FileZapperDescription {
            get {
                return ResourceManager.GetString("FileZapperDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Zapper is a network administration utility that allows you to remove files from a batch of specified computers at once. Great for cleaning up installation files and artifacts after a remote deployment..
        /// </summary>
        public static string FileZapperShortDescription {
            get {
                return ResourceManager.GetString("FileZapperShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;HP Warranty Reporter pulls HP warranty information from HP&amp;#8217;s website for serial numbers you specify. It includes support for list entry and can pull information for either computers or printers.&lt;/p&gt;
        ///
        ///    &lt;p&gt;Enter in the desired serial numbers into the left hand input window and click &amp;#8216;Find Warranties&amp;#8217; to get a list of products and their associated warranties. If the product is found in the HP database it will update on the ship date, warranty expiration date and the official model nam [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HpWarrantyDescription {
            get {
                return ResourceManager.GetString("HpWarrantyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP Warranty Reporter can take a serial number you provide and query HP&apos;s public warranty database for the warranty details. Includes PCs and Printer warranties.
        /// </summary>
        public static string HpWarrantyShortDescription {
            get {
                return ResourceManager.GetString("HpWarrantyShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintains compatibility with HP Warranty systems.
        /// </summary>
        public static string HpWarrantyVersion1 {
            get {
                return ResourceManager.GetString("HpWarrantyVersion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Service Tag reporter allows you to fetch the warranty information for single or multiple Dell devices directly from the Dell Warranty service. It includes support for list entry and a &amp;#8216;scouting&amp;#8217; feature that allows you to pull the service tag from another device remotely.&lt;/p&gt;
        ///
        ///    &lt;p&gt;Enter in the desired service tags into the left hand input window and click &amp;#8216;Query Tags&amp;#8217; to get a list of products and their associated warranties. If you need to find out the service tag of a remot [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ServiceTagDescription {
            get {
                return ResourceManager.GetString("ServiceTagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Tag Reporter is a great utility for finding, displaying and fetching Dell Warranty Information. Enter the Service Tag of a target PC (or fetch it from the network)and Service Tag Reporter will retreive the desired warranty information from Dell&apos;s Asset Service..
        /// </summary>
        public static string ServiceTagShortDescription {
            get {
                return ResourceManager.GetString("ServiceTagShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Changed output to ListView
        ///* Adjusted some internal processing.
        /// </summary>
        public static string ServiceTagVersion1 {
            get {
                return ResourceManager.GetString("ServiceTagVersion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Warranty fetch improvements
        ///* Invalid service tags no longer return warranties
        ///* Update to discard the new &apos;digital warranties&apos; being reported by Dell.
        /// </summary>
        public static string ServiceTagVersion10 {
            get {
                return ResourceManager.GetString("ServiceTagVersion10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Changed visual style to WPF
        ///* Changed output to a DataGrid
        ///* Added Find Serial Option.
        /// </summary>
        public static string ServiceTagVersion2 {
            get {
                return ResourceManager.GetString("ServiceTagVersion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Fixed Resizing Issue
        ///* Updated installer path.
        /// </summary>
        public static string ServiceTagVersion3 {
            get {
                return ResourceManager.GetString("ServiceTagVersion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Added Progress Bar
        ///* Added status Bar
        ///* Input is not split by line carriages
        ///* Fixed bug in spaces in serial numbers
        ///* Known Bug: Status bar not updating in each loop
        ///* Updated installer: now uses traditional instead of clickonce.
        /// </summary>
        public static string ServiceTagVersion4 {
            get {
                return ResourceManager.GetString("ServiceTagVersion4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Fixed GUI Elements
        ///* Datagrid now fills dynamicly
        ///* Fixed Installer shortcuts not showing proper icon.
        /// </summary>
        public static string ServiceTagVersion5 {
            get {
                return ResourceManager.GetString("ServiceTagVersion5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Updated code to fetch from Dell’s new SOAP service, resulting in faster reponses
        ///* Fixed model column in results to display series and model number
        ///* Various speed fixes
        ///* Installer temporarily removed for updating..
        /// </summary>
        public static string ServiceTagVersion6 {
            get {
                return ResourceManager.GetString("ServiceTagVersion6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * More Speed improvements
        ///* Fixed bug in resolving invalid hostnames with ‘Find Tag’ button
        ///* Fixed Gui issue – status now states when finished.
        /// </summary>
        public static string ServiceTagVersion7 {
            get {
                return ResourceManager.GetString("ServiceTagVersion7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Minor performance tweaks.
        /// </summary>
        public static string ServiceTagVersion8 {
            get {
                return ResourceManager.GetString("ServiceTagVersion8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Peformance upgrade
        ///* UI redone to be more user-friendly
        ///* Menu options added.
        /// </summary>
        public static string ServiceTagVersion9 {
            get {
                return ResourceManager.GetString("ServiceTagVersion9", resourceCulture);
            }
        }
    }
}
