//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfBurt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.Categories = new HashSet<Category>();
        }
    
        public int ArticleId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Link Links { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
    }
}
