//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfBurt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public string Tag { get; set; }
        public int CategoryId { get; set; }
        public string Id { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
