//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfBurt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public Link()
        {
            this.Article = new HashSet<Article>();
        }
    
        public int LinkId { get; set; }
        public string Url { get; set; }
        public string Caption { get; set; }
    
        public virtual ICollection<Article> Article { get; set; }
    }
}
