//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfBurt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Versions = new HashSet<Version>();
        }
    
        public int ProductId { get; set; }
        public string SourceLink { get; set; }
        public string IconUrl { get; set; }
        public string ImageUrl { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string FullDescription { get; set; }
    
        public virtual ICollection<Version> Versions { get; set; }
    }
}
